name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Rustfmt
    runs-on: codeberg-medium
    container:
      image: rust:1.85-bookworm
    steps:
      - name: Install Node.js and Git
        run: |
          apt-get update
          apt-get install -y nodejs git
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run fmt
        run: |
          rustup component add rustfmt
          cargo fmt --all
      - name: Commit and push changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "forgejo-actions[bot]"
            git config --global user.email "forgejo-actions[bot]@noreply.codeberg.org"
            git add .
            git commit -m "style: automatic formatting fix"
            git push
          fi

  clippy:
    name: Clippy
    runs-on: codeberg-medium
    needs: fmt
    container:
      image: rust:1.85-bookworm
    steps:
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y nodejs pkg-config libssl-dev
      - uses: actions/checkout@v4
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-clippy-${{ hashFiles('**/Cargo.lock') }}
      - name: Run clippy
        run: |
          rustup component add clippy
          cargo clippy --all-targets --all-features -- -D warnings

  test:
    name: Test
    runs-on: codeberg-medium
    needs: clippy
    container:
      image: rust:1.85-bookworm
    steps:
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y nodejs pkg-config libssl-dev
      - uses: actions/checkout@v4
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
      - name: Run tests
        run: cargo test

  build:
    name: Build Release
    runs-on: codeberg-medium
    needs: test
    container:
      image: rust:1.85-bookworm
    steps:
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y nodejs pkg-config libssl-dev
      - uses: actions/checkout@v4
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
      - name: Build release
        run: cargo build --release
