name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Rustfmt
    runs-on: codeberg-medium
    if: forgejo.event_name == 'pull_request'
    container:
      image: rust:1.85-bookworm
    steps:
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y nodejs
      - uses: actions/checkout@v4
      - name: Run fmt
        run: |
          rustup component add rustfmt
          cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: codeberg-medium
    needs: fmt
    if: forgejo.event_name == 'pull_request'
    container:
      image: rust:1.85-bookworm
    steps:
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y nodejs pkg-config libssl-dev
      - uses: actions/checkout@v4
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-clippy-${{ hashFiles('**/Cargo.lock') }}
      - name: Run clippy
        run: |
          rustup component add clippy
          cargo clippy --all-targets --all-features -- -D warnings

  test:
    name: Test
    runs-on: codeberg-medium
    needs: clippy
    if: forgejo.event_name == 'pull_request'
    container:
      image: rust:1.85-bookworm
    steps:
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y nodejs pkg-config libssl-dev
      - uses: actions/checkout@v4
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
      - name: Run tests
        run: cargo test

  build:
    name: Build Release
    runs-on: codeberg-medium
    needs: test
    if: forgejo.event_name == 'pull_request'
    container:
      image: rust:1.85-bookworm
    steps:
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y nodejs pkg-config libssl-dev
      - uses: actions/checkout@v4
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
      - name: Build release
        run: cargo build --release

  docker:
    name: Docker Build & Push
    runs-on: codeberg-medium
    if: forgejo.event_name == 'push' && forgejo.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Login to Codeberg Container Registry
        uses: docker/login-action@v3
        with:
          registry: codeberg.org
          username: ${{ forgejo.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            codeberg.org/${{ forgejo.repository }}:latest
            codeberg.org/${{ forgejo.repository }}:${{ forgejo.sha }}
